const initState = {
  projects: [
    { key: "webfirst", title: "Webfirst", body: ["Webfirst was initially created as a side project and it is still a work in progress, the main goal of Webfirst is to create websites for companies that need them using Gatsby as a headless CMS, also to provide a strong online presence for their company so they are at the top of the search results when someone searches for a specific keyword regarding their company.", "I choose to use Gatsby because it provides SEO and it follows the latest web standards and is optimized to be highly performant.", "I did run into a few errors along the way regarding the blogging page which was the hardest part of building this website but managed to finish it in the end and now I can upload Markup blogs to the blogging page and it will display them from the latest posts to the oldest posts.", "I am still working on filling in the content with text on the services page and about page. I am also still setting up Google My Business page so the website can have a larger online presence when people search for web development in New Zealand.", "I have chosen to make the websites very cheap because I want to attract new businesses and gather good reviews first.", "Webfirst mainly provides front-end services and SEO."]},
    { key: "codification", title: "Codification", body: ["For my very first freelancing job on UpWork I was invited to help with front-end development for the company Codification.io. This website is for teaching employees of companies about cloud services such as Kubernetes and Azure etc... I mainly contributed to front end development on codification.io and coficication.bootcamp.io.", "Work: Overall the work was a great experience and I enjoyed doing it, it taught me a lot about working with teams in a development environment, I worked with 3 other developers during my time here.", "Azure DevOps: I was given access to Azure DevOps to push my work through so that it can be reviewed and uploaded to the live project. This taught me a lot about the Git workflow and I learnt how to merge, use push and pull requests in a live environment, and use Git effectively from the command line. I also learnt a lot about how large websites are hosted and used with cloud services like Azure.", "React: I was primarily focused on using React for the front end development of codification.io and bootcamp.codification.io. There were mockups done by designers already on Figma.com and we each worked on one page at a time. Doing the front end design using react wasn’t too hard, however I started struggling a bit when it came to form validation for the sign-in/sign-up pages. I ended up making it through that part though and learnt a lot about using hooks, and how you can also use the form-validator plugin from npmjs.com.","Tailwind: Tailwind was new to me before this project and I learnt it very quickly and now use it a lot for my personal projects as it is a great CSS framework."]},
    { key: "gdrive", title: "Google Drive Clone", body: ["This project is a clone of Google Drive and it allows you to upload images and files and display them on the front page. It uses Google authentication for logging in. When you upload your file it submits it to the Firestore Database using Firebase.", "I am still working on making it so you can upload files privately using a Google account, right now, all uploads are public. I am also working on persistence so that when you refresh the page you are still logged in. And I am still creating all the other pages.", "The main challenges of this project for me was creating a collection in Firebase, I ran into an issue where I could not upload files, this was because the permission rules were set so that you could only upload files directly into firebase, but I changed the rule permissions and it worked. I also was trying to figure out how to display the file size in all the different data sets to be a readable file size, and I found a good article on StackOverflow which showed me how to do this. "] },
    { key: "", title: "post4", body: "body4" },
  ],
};

const rootReducer = (state = initState, action) => {
  return state;
};

export default rootReducer;
